BOOTSTRAP = ./subModules/bootstrap/

build: clean bootstrap html siteAssets

bootstrap: node_modules
	@echo "\nBuilding Assets..."
	@mkdir ./tmp
	@cp -r ${BOOTSTRAP}* ./tmp/
	{{#bootstrapVariablesFile}}
	@cp {{{bootstrapVariablesFile}}} ./tmp/less/variables.less
	{{/bootstrapVariablesFile}}
	{{#extraLessFiles}}
	@cp {{{dir}}}/{{{file}}} ./tmp/less/{{{file}}}
	@echo "\n@import \"{{{file}}}\";" >> ./tmp/less/bootstrap.less 
	{{/extraLessFiles}}
	
	@cd ./tmp; ln -s ../node_modules; grunt dist;
	@mkdir -p ./build/assets
	@cp -R ./tmp/dist/* ./build/assets

# TODO change so we're not running the tests anymore. But don't want to run index.js either as that will re-run make
html: node_modules
	@echo "\nBuild HTML..."
	@node ./lib/run.js

siteAssets: 
	@echo "\nCopy site specific assets..."
	@rsync -a templates/assets/ build/assets/

clean:
	@echo "\nDelete previous build"
	@rm -rf ./tmp/
	@rm -rf ./build/

node_modules:
	npm install


.PHONY: build


